##Cara Install

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


##Import Numpy

In [ ]:
import numpy as np
print(np.__version__)

1.21.6


##Create

In [ ]:
# Satu Dimensi
arr1 = np.array([1,2,3,4,5]) #satu dimensi

arr2 = np.array([[1,2,3],
                 [2,3,4],
                 [5,6,7]]) #dua dimensi

arr3 = np.array([[[1,2,3],
                  [2,4,5],
                  ],
                 [[5,6,7],
                  [8,9,10],
                 ],
                 [[5,6,7],
                  [8,9,10],
                  ]]) # tiga dimensi

arr4 = np.random.rand(2,3,2) #generate otomatis

# Mengetahui dimensi
print(arr1.shape) # 1 baris 5 kolom
print(arr2.shape) # 3 baris 3 kolom
print(arr3.shape) # Banyaknya 3, dalamnya isi 2, dimensi 3 
print(arr4.shape)
arr4

(5,)
(3, 3)
(3, 2, 3)
(2, 3, 2)


array([[[0.90881431, 0.62392621],
        [0.23625834, 0.41249688],
        [0.56609956, 0.85712616]],

       [[0.5535594 , 0.76591192],
        [0.46840586, 0.07459092],
        [0.68573864, 0.23181333]]])

##Read

In [ ]:
# Buat array dengan angka random
data = np.random.rand(3,3)

array([[0.24649069, 0.05936864, 0.10603698],
       [0.37212265, 0.09437455, 0.67106503],
       [0.0571417 , 0.2076138 , 0.29996769]])

In [ ]:
shape = data.shape
size = data.size
types = data.dtype

# Print
print(shape) # bentuk
print(size) # total jumlah
print(types) # tipe data

(3, 3)
9
float64


In [ ]:
# Slicing 
arr = data[0]             # ambil baris pertama
slicer = data[0][0:2]     # baris pertama, kolom ditentukan
reverse = data[-1]        # data terakhir
single_value = data[0][0] # ambil single value


# print(arr)
# print(slicer)
# print(reverse)
# print(single_value)

In [ ]:
data

array([[0.24649069, 0.05936864, 0.10603698],
       [0.37212265, 0.09437455, 0.67106503],
       [0.0571417 , 0.2076138 , 0.29996769]])

##Update

In [ ]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

print(list1,'\n')
print(list2)

[0.69145716 0.71409086 0.89360305 0.18763831 0.34343267 0.75259561
 0.77291263 0.10472801 0.07207362 0.76242962] 

[0.55144953 0.84124027 0.0218937  0.25022515 0.87875774 0.8363917
 0.37439744 0.16931536 0.94021792 0.86694808]


In [ ]:
# Basic Math
add = np.add(list1, list2)      # Pertambahan
sub = np.subtract(list1,list2)  # Pengurangan
div = np.divide(list1,list2)    # Pembagian
mult = np.multiply(list1,list2) # Perkalian
dot = np.dot(list1,list2)       # Dot produk

add

array([1.2429067 , 1.55533113, 0.91549675, 0.43786346, 1.22219041,
       1.58898731, 1.14731007, 0.27404337, 1.01229154, 1.6293777 ])

In [ ]:
# Stat Functions
sqrt = np.sqrt(25) # akar
ab = np.abs(-2) # absolut   
power = np.power(2,7) # pangkat
log = np.log(25) # logaritma
exp = np.exp([2,3]) # exponen
mins = np.min(list1) # minimum
maxs = np.max(list1) # maksimum

mins

0.07207362048097732

In [ ]:
data

array([[0.24649069, 0.05936864, 0.10603698],
       [0.37212265, 0.09437455, 0.67106503],
       [0.0571417 , 0.2076138 , 0.29996769]])

In [ ]:
# update value
data[0][0] = 10

In [ ]:
data

array([[10.        ,  0.05936864,  0.10603698],
       [ 0.37212265,  0.09437455,  0.67106503],
       [ 0.0571417 ,  0.2076138 ,  0.29996769]])

In [ ]:
# Mengurutkan data
data.sort()
data

array([[ 0.05936864,  0.10603698, 10.        ],
       [ 0.09437455,  0.37212265,  0.67106503],
       [ 0.0571417 ,  0.2076138 ,  0.29996769]])

In [ ]:
print(data.shape) # dimensi data

(3, 3)


In [ ]:
data = data.reshape((1,1,-1)) # mengubah dimensi
data.shape

(1, 1, 9)

In [ ]:
# Menambah data
zeroes = np.zeros(8)
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [ ]:
zeroes = np.insert(zeroes,2,1) # var ,indeks, value
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


##Delete

In [ ]:
data2 = np.random.rand(3,3,2)
data2

array([[[0.04108795, 0.59974023],
        [0.87421233, 0.24448258],
        [0.06148898, 0.44774585]],

       [[0.98541712, 0.1325455 ],
        [0.15222603, 0.39743091],
        [0.30632144, 0.3179814 ]],

       [[0.85020946, 0.09304798],
        [0.13969281, 0.47211463],
        [0.11341554, 0.92003622]]])

In [ ]:
data2 = np.delete(data2, 0, axis=1)
data2

array([[[0.87421233, 0.24448258],
        [0.06148898, 0.44774585]],

       [[0.15222603, 0.39743091],
        [0.30632144, 0.3179814 ]],

       [[0.13969281, 0.47211463],
        [0.11341554, 0.92003622]]])